services:
  postgres:
    image: postgres:16-alpine
    container_name: serplantas_db
    environment:
      POSTGRES_USER: serplantas
      POSTGRES_PASSWORD: serplantas123
      POSTGRES_DB: serplantas_db
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U serplantas" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
